stages:
    - update

Release:server:
  stage: update
  environment:
    name: update
  script:
    - echo -e "sudo -i\ncd ..\ncd /var/www/html\ngit init\ngit clone -c http.sslverify=false https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git\ncd opencart\ngit checkout release-v1.2\ncd upload\nmv config-dist.php config.php\ncd admin\nmv config-dist.php config.php\nchown -R www-data:www-data /var/www/html/opencart\nnginx -t\nsystemctl restart nginx">gitclone.sh

    - chmod +x gitclone.sh
    - apk add sshpass
    - export SSHPASS='ubuntu'
    - sshpass -e ssh -oStrictHostKeyChecking=no -t ubuntu@10.0.100.191<gitclone.sh

    - echo -e "sudo -i\ncd ..\ngit config --global --add safe.directory /var/www/html/opencart\ncd /var/www/html/opencart\ngit remote add upstream https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git\ngit pull upstream release-v1.2\ngit status\ngit push https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git\ngit status">update.sh
    - chmod +x update.sh
    - apk add sshpass
    - export SSHPASS='ubuntu'
    - sshpass -e ssh -oStrictHostKeyChecking=no -t ubuntu@10.0.100.191<update.sh
  when: manual

    
    
 
