stages:
    - update
    

Release:server:
  stage: update
  environment:
    name: Release
  script:
    
    #- gitlab-terraform apply -target=harvester_virtualmachine.opencart-server
    - echo "sudo -i\ncd ..\ngit config --global --add safe.directory /var/www/html/opencart\ncd /var/www/html/opencart\ngit remote add upstream https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git\ngit pull upstream release-v1.1\ngit status\ngit push https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git">update.sh
    - chmod +x update.sh
    - apk add sshpass
    - export SSHPASS='ubuntu'
    - sshpass -e ssh -oStrictHostKeyChecking=no -t ubuntu@10.0.100.191<update.sh
# for opencart.conf file
    
    
 
