stages:
    - update

Release:server:
  stage: update
  environment:
    name: update
  script:
    
    - echo -e "sudo -i\ncd ..\ncd var/www/html\ngit clone -c http.sslverify=false https://ankita:Ankita402109@git.os3.coe.com/application-testing/opencart.git\ngit checkout release-v1.1\ngit config --global --add safe.directory /var/www/html/opencart\ncd /var/www/html/opencart\ngit remote add upstream https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git\ngit pull upstream release-v1.1\ngit status\ngit push https://ankita:Ankita%402109@git.os3.coe.com/application-testing/opencart.git">update.sh
    - chmod +x update.sh
    - apk add sshpass
    - export SSHPASS='ubuntu'
    - sshpass -e ssh -oStrictHostKeyChecking=no -t ubuntu@10.0.100.191<update.sh
  when: manual

    
    
 
